name: profile
description: "Profile page for my portfolio"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  url_launcher: ^6.3.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  pdf: ^3.11.2
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/flags/
    - assets/photos/
    - assets/services/
    - assets/fonts/
  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Italic.ttf
          style: italic
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-Semibold.ttf
          weight: 500
    - family: Symbol
      fonts:
        - asset: assets/fonts/symbol.ttf